### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by tytremblay** [nwalters512/wildrank-android#11]
I'm trying to run wildrank for the first time on an AVD and running into this error:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wildstang.wildrank.android/org.wildstang.wildrank.android.activities.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020009`

Any help would be appreciated.

**Comment by nwalters512** [comment]
This project hasn't been supported for several years, you probably want to check out https://github.com/wildstang/wildrank-android instead. I'll add a deprecation notice to this readme!
